kind: pipeline
type: docker
name: default

steps:
  - name: build-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t lms-backend .

  - name: install-docker-compose
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - apk add --no-cache curl py3-pip python3 libc6-compat
      - pip3 install --upgrade pip
      - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
      - docker-compose --version

  - name: deploy
    image: docker/compose:1.29.2
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: hostdata
        path: /mnt/data
    commands:
      - cd /mnt/data/deployments/lms-backend || exit 1
      - git pull origin master
      - docker-compose down
      - docker-compose build
      - docker-compose up -d

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: hostdata
    host:
      path: /mnt/data