kind: pipeline
type: docker
name: default

steps:
  - name: build-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t lms-backend .

  - name: deploy
    image: alpine:latest
    environment:
      SSH_HOST:
        from_secret: ssh_host
      SSH_USER:
        from_secret: ssh_username
      SSH_PASS:
        from_secret: ssh_password
    commands:
      - apk add --no-cache openssh sshpass
      - |
        echo username=$SSH_USER
        echo password=$SSH_PASS
        echo host=$SSH_HOST
        test -n "$SSH_PASS" || { echo "SSH_PASS is empty"; exit 1; }
        sshpass -vv -p $SSH_PASS ssh -o StrictHostKeyChecking=no -p 22 $SSH_USER@$SSH_HOST "
          cd /mnt/data/deployments/lms-backend
          git pull origin master
          docker-compose down
          docker-compose build
          docker-compose up -d
          docker system prune -f
        "

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock