kind: pipeline
type: docker
name: default

steps:
  - name: build-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t lms-backend .

  - name: install-docker-compose
    image: docker:latest
    commands:
      - apk add --no-cache curl
      - curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
      - echo "Current PATH: $PATH"
      - ls -l /usr/local/bin
      - chmod +x /usr/local/bin/docker-compose
      - echo "docker-compose version:"
      - docker-compose --version

  - name: deploy
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - apk add --no-cache curl
      - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - export PATH=$PATH:/usr/local/bin
      - docker-compose --version
      - cd /mnt/data/deployments/lms-backend || exit 1
      - git pull origin master
      - docker-compose down
      - docker-compose build
      - docker-compose up -d
      - docker system prune -f
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: hostdata
    host:
      path: /mnt/data
