kind: pipeline
type: docker
name: default

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: app_directory
    host:
      path: /mnt/data/deployments/lms-backend 

steps:
  - name: build
    image: docker:cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: app_directory
        path: /app
    commands:
      - cd /app
      - docker build -t lms-backend .

  - name: deploy
    image: docker:cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: app_directory
        path: /app
    commands:
      - cd /app
      - docker-compose down
      - docker-compose build --no-cache
      - docker-compose up -d
      - docker system prune -f